import { nanoid } from "nanoid";
import { loadJobConfig } from "../core/config.js";
import type { JobConfig } from "../core/types.js";
import { sendNotifications } from "../notifications/dispatcher.js";
import { extractIssueNumber, postIssueComment } from "../notifications/issue-comment.js";
import { GitOpsError } from "../util/errors.js";
import { execCommand } from "../util/exec.js";
import { paths } from "../util/paths.js";
import { loadRunContext, type RunContext } from "./context-store.js";
import { checkBudget } from "./cost-tracker.js";
import {
	attemptRebase,
	checkoutExistingBranch,
	createBranch,
	createPR,
	hasChanges,
	pullLatest,
	pushBranch,
} from "./git-ops.js";
import type { ScoredIssue } from "./issue-triage.js";
import { triageIssues } from "./issue-triage.js";
import { acquireLock } from "./lock.js";
import { runPipeline } from "./pipeline.js";
import { writeRunLog } from "./logger.js";
import { checkPendingPRFeedback, postPRComment } from "./pr-feedback.js";
import {
	buildFeedbackPrompt,
	buildSystemPrompt,
	buildTriagedWorkPrompt,
} from "./prompt-builder.js";
import { buildAllowedTools, spawnClaude } from "./spawner.js";
import type { PipelineResult, PRFeedbackContext, RunResult, SpawnResult } from "./types.js";

/**
 * Format a duration in milliseconds to a human-readable "Xm Ys" string.
 */
function formatDuration(ms: number): string {
	const totalSeconds = Math.floor(ms / 1000);
	const minutes = Math.floor(totalSeconds / 60);
	const seconds = totalSeconds % 60;
	return `${minutes}m ${seconds}s`;
}

/**
 * Build a PR body from spawn result and job config.
 */
function buildPRBody(spawnResult: SpawnResult, config: JobConfig): string {
	return [
		`## Summary\n\n${spawnResult.summary}`,
		`## Details\n\n- **Job:** ${config.name} (${config.id})\n- **Branch:** ${config.repo.branch}\n- **Turns used:** ${spawnResult.numTurns}\n- **Cost:** $${spawnResult.costUsd.toFixed(4)}\n- **Duration:** ${formatDuration(spawnResult.durationMs)}`,
		"---\n*Generated by [claude-auto](https://github.com/your-org/claude-auto)*",
	].join("\n\n");
}

/**
 * Build a PR body from pipeline result and job config.
 * Shows per-stage cost/duration breakdown and review verdict.
 */
function buildPipelinePRBody(pipelineResult: PipelineResult, config: JobConfig): string {
	const stageLines = pipelineResult.stages.map(
		(s) =>
			`- **${s.stage}**: ${s.spawnResult.numTurns} turns, $${s.spawnResult.costUsd.toFixed(4)}, ${formatDuration(s.spawnResult.durationMs)}`,
	);
	return [
		`## Summary\n\n${pipelineResult.summary}`,
		`## Pipeline Stages\n\n${stageLines.join("\n")}`,
		`## Details\n\n- **Job:** ${config.name} (${config.id})\n- **Review verdict:** ${pipelineResult.reviewVerdict}\n- **Total cost:** $${pipelineResult.totalCostUsd.toFixed(4)}\n- **Total duration:** ${formatDuration(pipelineResult.totalDurationMs)}`,
		"---\n*Generated by [claude-auto](https://github.com/your-org/claude-auto) (pipeline mode)*",
	].join("\n\n");
}

/**
 * Check for divergence before push and attempt rebase if needed.
 * Returns whether push can proceed and any conflict file names.
 *
 * This is best-effort: if the rebase check itself fails, we allow
 * the push to proceed (pushBranch will fail naturally if there is
 * a real conflict).
 */
async function handlePrePushRebase(
	repoPath: string,
	baseBranch: string,
	remote: string,
): Promise<{ canPush: boolean; conflicts?: string[] }> {
	try {
		const rebaseResult = await attemptRebase(repoPath, baseBranch, remote);
		if (rebaseResult.diverged && !rebaseResult.rebased) {
			return { canPush: false, conflicts: rebaseResult.conflicts };
		}
		return { canPush: true };
	} catch {
		// Rebase check is best-effort; if it fails, proceed with push
		// (pushBranch will fail naturally if there's a real conflict)
		return { canPush: true };
	}
}

/**
 * Execute a full autonomous run cycle for a job.
 *
 * Sequence: lock -> config -> enabled check -> budget check -> pullLatest ->
 * check PR feedback (priority) -> if feedback: iterate on PR -> else: triage issues ->
 * create branch -> spawn Claude -> check changes -> push/PR -> log -> unlock
 *
 * @param jobId - The job identifier to run
 * @returns RunResult with status indicating outcome
 */
export async function executeRun(jobId: string): Promise<RunResult> {
	const startedAt = new Date().toISOString();
	const runId = nanoid(12);
	const startTime = Date.now();

	// Step 1: Acquire lock
	const releaseLock = await acquireLock(jobId);
	if (!releaseLock) {
		const result: RunResult = {
			status: "locked",
			jobId,
			runId,
			startedAt,
			completedAt: new Date().toISOString(),
			durationMs: Date.now() - startTime,
		};
		await writeRunLog(jobId, result);
		return result;
	}

	let branchName: string | undefined;
	let isFeedbackBranch = false;
	let config: JobConfig | undefined;

	try {
		// Step 2: Load config
		config = await loadJobConfig(paths.jobConfig(jobId));

		// Defense-in-depth: check if job is paused
		if (!config.enabled) {
			const result: RunResult = {
				status: "paused",
				jobId,
				runId,
				startedAt,
				completedAt: new Date().toISOString(),
				durationMs: Date.now() - startTime,
			};
			await writeRunLog(jobId, result);
			return result;
		}

		// Step 2.5: Check cumulative budget
		if (config.budget) {
			const exceeded = checkBudget(jobId, config.budget);
			if (exceeded) {
				const result: RunResult = {
					status: "budget-exceeded",
					jobId,
					runId,
					startedAt,
					completedAt: new Date().toISOString(),
					durationMs: Date.now() - startTime,
					model: config.model,
				};
				await writeRunLog(jobId, result);
				await sendNotifications(config, result).catch(() => {});
				return result;
			}
		}

		// Step 3: Pull latest
		await pullLatest(config.repo.path, config.repo.branch, config.repo.remote);

		// Step 3.5: Check for pending PR feedback (PRFB-01)
		let feedback: PRFeedbackContext | null = null;
		try {
			feedback = await checkPendingPRFeedback(
				config.repo.path,
				config.id,
				config.maxFeedbackRounds ?? 3,
			);
		} catch {
			// PR feedback check is best-effort; fall through to normal work
		}

		if (feedback) {
			// --- PR FEEDBACK PATH (PRFB-02) ---
			const nextRound = feedback.currentRound + 1;
			const maxRounds = config.maxFeedbackRounds ?? 3;

			// Check if max rounds exceeded BEFORE doing work (defense-in-depth)
			if (nextRound > maxRounds) {
				// Post "needs human review" comment and return
				await postPRComment(
					config.repo.path,
					feedback.number,
					`Claude Auto has reached the maximum feedback iteration limit (${maxRounds} rounds). This PR needs human review.\n\n---\n*Automated by claude-auto*`,
				).catch(() => {});

				const result: RunResult = {
					status: "needs-human-review",
					jobId,
					runId,
					startedAt,
					completedAt: new Date().toISOString(),
					durationMs: Date.now() - startTime,
					prNumber: feedback.number,
					feedbackRound: nextRound,
					model: config.model,
				};
				await writeRunLog(jobId, result);
				await sendNotifications(config, result).catch(() => {});
				return result;
			}

			// Checkout existing PR branch (PRFB-02)
			await checkoutExistingBranch(config.repo.path, feedback.headRefName);
			branchName = feedback.headRefName;
			isFeedbackBranch = true;

			// Load context and build feedback prompt
			let runContext: RunContext[] = [];
			try {
				runContext = loadRunContext(jobId);
			} catch {
				// Context loading is best-effort
			}

			const feedbackPrompt = buildFeedbackPrompt(config, feedback, runContext);
			const systemPrompt = buildSystemPrompt(config);
			const allowedTools = buildAllowedTools(config);

			// Spawn Claude to address feedback
			const spawnResult = await spawnClaude({
				cwd: config.repo.path,
				prompt: feedbackPrompt,
				maxTurns: config.guardrails.maxTurns,
				maxBudgetUsd: config.guardrails.maxBudgetUsd,
				allowedTools,
				appendSystemPrompt: systemPrompt,
				model: config.model,
			});

			// Push to same branch (PRFB-04)
			const changed = await hasChanges(config.repo.path);
			if (changed) {
				await pushBranch(config.repo.path, feedback.headRefName);
				// Post PR comment summarizing changes (PRFB-04)
				const commentBody = `## Feedback Addressed (Round ${nextRound}/${maxRounds})\n\n${spawnResult.summary}\n\n---\n*Automated by claude-auto*`;
				await postPRComment(config.repo.path, feedback.number, commentBody).catch(() => {});
			}

			const result: RunResult = {
				status: changed ? "success" : "no-changes",
				jobId,
				runId,
				startedAt,
				completedAt: new Date().toISOString(),
				durationMs: Date.now() - startTime,
				prUrl: feedback.url,
				summary: spawnResult.summary,
				costUsd: spawnResult.costUsd,
				numTurns: spawnResult.numTurns,
				sessionId: spawnResult.sessionId,
				branchName: feedback.headRefName,
				prNumber: feedback.number,
				feedbackRound: nextRound,
				model: config.model,
			};

			await writeRunLog(jobId, result);
			await sendNotifications(config, result).catch(() => {});
			return result;
		}

		// --- NORMAL WORK PATH (with triage enhancement) ---

		// Step 4: Create work branch
		branchName = await createBranch(config.repo.path, jobId);

		// Step 4.5: Load cross-run context
		let runContext: RunContext[] = [];
		try {
			runContext = loadRunContext(jobId);
		} catch {
			// Context loading is best-effort
		}

		// Step 4.6: Triage issues (TRIG-01, TRIG-02, TRIG-03)
		let triaged: ScoredIssue[] = [];
		try {
			const previousIssues = runContext
				.filter((c) => c.issue_number != null)
				.map((c) => c.issue_number as number);
			triaged = await triageIssues(config.repo.path, previousIssues);
		} catch {
			// Triage is best-effort; fall through to generic prompt
		}

		// Step 5: Pipeline or single-spawn path
		if (config.pipeline?.enabled) {
			// --- PIPELINE PATH (PIPE-01, PIPE-02, PIPE-03) ---
			const pipelineResult = await runPipeline(config, config.repo.path, branchName, runContext, triaged);
			const changed = await hasChanges(config.repo.path);

			let prUrl: string | undefined;
			if (changed) {
				// Check for divergence before push (MRGC-01, MRGC-02)
				const { canPush, conflicts } = await handlePrePushRebase(
					config.repo.path,
					config.repo.branch,
					config.repo.remote,
				);
				if (!canPush) {
					// MRGC-03: Report merge conflict
					const result: RunResult = {
						status: "merge-conflict",
						jobId,
						runId,
						startedAt,
						completedAt: new Date().toISOString(),
						durationMs: Date.now() - startTime,
						branchName,
						error: `Merge conflict with ${config.repo.branch}. Conflicting files: ${(conflicts ?? []).join(", ") || "unknown"}`,
						costUsd: pipelineResult.totalCostUsd,
						numTurns: pipelineResult.stages.reduce((sum, s) => sum + s.spawnResult.numTurns, 0),
						model: config.model,
						pipelineStages: pipelineResult.stages.map((s) => ({
							stage: s.stage,
							costUsd: s.spawnResult.costUsd,
							durationMs: s.spawnResult.durationMs,
							numTurns: s.spawnResult.numTurns,
						})),
					};
					await writeRunLog(jobId, result);
					await sendNotifications(config, result).catch(() => {});
					return result;
				}

				await pushBranch(config.repo.path, branchName);
				const prTitle = `[claude-auto] ${pipelineResult.summary.slice(0, 72)}`;
				const prBody = buildPipelinePRBody(pipelineResult, config);
				prUrl = await createPR(config.repo.path, branchName, config.repo.branch, prTitle, prBody);
			}

			const result: RunResult = {
				status: changed ? "success" : "no-changes",
				jobId,
				runId,
				startedAt,
				completedAt: new Date().toISOString(),
				durationMs: Date.now() - startTime,
				prUrl,
				summary: pipelineResult.summary,
				costUsd: pipelineResult.totalCostUsd,
				numTurns: pipelineResult.stages.reduce((sum, s) => sum + s.spawnResult.numTurns, 0),
				sessionId: pipelineResult.stages[pipelineResult.stages.length - 1]?.spawnResult.sessionId,
				branchName,
				model: config.model,
				pipelineStages: pipelineResult.stages.map((s) => ({
					stage: s.stage,
					costUsd: s.spawnResult.costUsd,
					durationMs: s.spawnResult.durationMs,
					numTurns: s.spawnResult.numTurns,
				})),
			};

			await writeRunLog(jobId, result);
			await sendNotifications(config, result).catch(() => {});

			// Extract issue number from pipeline summary
			const pipelineIssueNumber = pipelineResult.summary
				? extractIssueNumber(pipelineResult.summary)
				: undefined;
			if (pipelineIssueNumber) {
				await postIssueComment({
					repoPath: config.repo.path,
					issueNumber: pipelineIssueNumber,
					status: result.status,
					prUrl: result.prUrl,
					summary: result.summary,
					jobName: config.name,
				}).catch(() => {});
			}

			return result;
		}

		// --- SINGLE-SPAWN PATH (existing behavior) ---

		// Step 5: Build prompt (use triaged version)
		const workPrompt = buildTriagedWorkPrompt(config, triaged, runContext);
		const systemPrompt = buildSystemPrompt(config);
		const allowedTools = buildAllowedTools(config);

		// Step 6: Spawn Claude
		const spawnResult = await spawnClaude({
			cwd: config.repo.path,
			prompt: workPrompt,
			maxTurns: config.guardrails.maxTurns,
			maxBudgetUsd: config.guardrails.maxBudgetUsd,
			allowedTools,
			appendSystemPrompt: systemPrompt,
			model: config.model,
		});

		// Step 7: Check for changes
		const changed = await hasChanges(config.repo.path);

		let prUrl: string | undefined;
		if (changed) {
			// Step 7.5: Check for divergence before push (MRGC-01, MRGC-02)
			const { canPush, conflicts } = await handlePrePushRebase(
				config.repo.path,
				config.repo.branch,
				config.repo.remote,
			);
			if (!canPush) {
				// MRGC-03: Report merge conflict
				const result: RunResult = {
					status: "merge-conflict",
					jobId,
					runId,
					startedAt,
					completedAt: new Date().toISOString(),
					durationMs: Date.now() - startTime,
					branchName,
					error: `Merge conflict with ${config.repo.branch}. Conflicting files: ${(conflicts ?? []).join(", ") || "unknown"}`,
					costUsd: spawnResult.costUsd,
					numTurns: spawnResult.numTurns,
					model: config.model,
				};
				await writeRunLog(jobId, result);
				await sendNotifications(config, result).catch(() => {});
				return result;
			}

			// Step 8: Push and create PR
			await pushBranch(config.repo.path, branchName);
			const prTitle = `[claude-auto] ${spawnResult.summary.slice(0, 72)}`;
			const prBody = buildPRBody(spawnResult, config);
			prUrl = await createPR(config.repo.path, branchName, config.repo.branch, prTitle, prBody);
		}

		// Extract issue number from summary if present
		const issueNumber = spawnResult.summary ? extractIssueNumber(spawnResult.summary) : undefined;

		const result: RunResult = {
			status: changed ? "success" : "no-changes",
			jobId,
			runId,
			startedAt,
			completedAt: new Date().toISOString(),
			durationMs: Date.now() - startTime,
			prUrl,
			summary: spawnResult.summary,
			costUsd: spawnResult.costUsd,
			numTurns: spawnResult.numTurns,
			sessionId: spawnResult.sessionId,
			branchName,
			issueNumber,
			model: config.model,
		};

		await writeRunLog(jobId, result);

		// Best-effort notifications (never fail the run)
		await sendNotifications(config, result).catch(() => {});
		if (issueNumber) {
			await postIssueComment({
				repoPath: config.repo.path,
				issueNumber,
				status: result.status,
				prUrl: result.prUrl,
				summary: result.summary,
				jobName: config.name,
			}).catch(() => {});
		}

		return result;
	} catch (error) {
		const isGitError = error instanceof GitOpsError;
		const result: RunResult = {
			status: isGitError ? "git-error" : "error",
			jobId,
			runId,
			startedAt,
			completedAt: new Date().toISOString(),
			durationMs: Date.now() - startTime,
			error: error instanceof Error ? error.message : String(error),
			branchName,
		};

		await writeRunLog(jobId, result).catch(() => {}); // Don't fail on log write error

		// Best-effort notifications on error
		if (config) {
			await sendNotifications(config, result).catch(() => {});
			const errorIssueNumber = result.summary ? extractIssueNumber(result.summary) : undefined;
			if (errorIssueNumber) {
				await postIssueComment({
					repoPath: config.repo.path,
					issueNumber: errorIssueNumber,
					status: result.status,
					error: result.error,
					jobName: config.name,
				}).catch(() => {});
			}
		}

		// Cleanup: if we created a branch (not a feedback branch) but failed, try to go back to base branch
		if (branchName && config && !isFeedbackBranch) {
			try {
				await execCommand("git", ["-C", config.repo.path, "checkout", config.repo.branch]);
				await execCommand("git", ["-C", config.repo.path, "branch", "-D", branchName]);
			} catch {
				// Cleanup is best-effort
			}
		}

		return result;
	} finally {
		await releaseLock();
	}
}
