import { nanoid } from "nanoid";
import { acquireLock } from "./lock.js";
import { pullLatest, createBranch, hasChanges, pushBranch, createPR } from "./git-ops.js";
import { spawnClaude, buildAllowedTools } from "./spawner.js";
import { buildWorkPrompt, buildSystemPrompt } from "./prompt-builder.js";
import { writeRunLog } from "./logger.js";
import { loadJobConfig } from "../core/config.js";
import { paths } from "../util/paths.js";
import { execCommand } from "../util/exec.js";
import { GitOpsError } from "../util/errors.js";
import { sendNotifications } from "../notifications/dispatcher.js";
import { extractIssueNumber, postIssueComment } from "../notifications/issue-comment.js";
import type { JobConfig } from "../core/types.js";
import type { RunResult, SpawnResult } from "./types.js";

/**
 * Format a duration in milliseconds to a human-readable "Xm Ys" string.
 */
function formatDuration(ms: number): string {
	const totalSeconds = Math.floor(ms / 1000);
	const minutes = Math.floor(totalSeconds / 60);
	const seconds = totalSeconds % 60;
	return `${minutes}m ${seconds}s`;
}

/**
 * Build a PR body from spawn result and job config.
 */
function buildPRBody(spawnResult: SpawnResult, config: JobConfig): string {
	return [
		`## Summary\n\n${spawnResult.summary}`,
		`## Details\n\n- **Job:** ${config.name} (${config.id})\n- **Branch:** ${config.repo.branch}\n- **Turns used:** ${spawnResult.numTurns}\n- **Cost:** $${spawnResult.costUsd.toFixed(4)}\n- **Duration:** ${formatDuration(spawnResult.durationMs)}`,
		"---\n*Generated by [claude-auto](https://github.com/your-org/claude-auto)*",
	].join("\n\n");
}

/**
 * Execute a full autonomous run cycle for a job.
 *
 * Sequence: lock -> config -> git pull -> branch -> spawn Claude ->
 * check changes -> push/PR -> log -> unlock
 *
 * @param jobId - The job identifier to run
 * @returns RunResult with status indicating outcome
 */
export async function executeRun(jobId: string): Promise<RunResult> {
	const startedAt = new Date().toISOString();
	const runId = nanoid(12);
	const startTime = Date.now();

	// Step 1: Acquire lock
	const releaseLock = await acquireLock(jobId);
	if (!releaseLock) {
		const result: RunResult = {
			status: "locked",
			jobId,
			runId,
			startedAt,
			completedAt: new Date().toISOString(),
			durationMs: Date.now() - startTime,
		};
		await writeRunLog(jobId, result);
		return result;
	}

	let branchName: string | undefined;
	let config: JobConfig | undefined;

	try {
		// Step 2: Load config
		config = await loadJobConfig(paths.jobConfig(jobId));

		// Step 3: Pull latest
		await pullLatest(config.repo.path, config.repo.branch, config.repo.remote);

		// Step 4: Create work branch
		branchName = await createBranch(config.repo.path, jobId);

		// Step 5: Build prompt and tools
		const workPrompt = buildWorkPrompt(config);
		const systemPrompt = buildSystemPrompt(config);
		const allowedTools = buildAllowedTools(config);

		// Step 6: Spawn Claude
		const spawnResult = await spawnClaude({
			cwd: config.repo.path,
			prompt: workPrompt,
			maxTurns: config.guardrails.maxTurns,
			maxBudgetUsd: config.guardrails.maxBudgetUsd,
			allowedTools,
			appendSystemPrompt: systemPrompt,
		});

		// Step 7: Check for changes
		const changed = await hasChanges(config.repo.path);

		let prUrl: string | undefined;
		if (changed) {
			// Step 8: Push and create PR
			await pushBranch(config.repo.path, branchName);
			const prTitle = `[claude-auto] ${spawnResult.summary.slice(0, 72)}`;
			const prBody = buildPRBody(spawnResult, config);
			prUrl = await createPR(
				config.repo.path,
				branchName,
				config.repo.branch,
				prTitle,
				prBody,
			);
		}

		// Extract issue number from summary if present
		const issueNumber = spawnResult.summary ? extractIssueNumber(spawnResult.summary) : undefined;

		const result: RunResult = {
			status: changed ? "success" : "no-changes",
			jobId,
			runId,
			startedAt,
			completedAt: new Date().toISOString(),
			durationMs: Date.now() - startTime,
			prUrl,
			summary: spawnResult.summary,
			costUsd: spawnResult.costUsd,
			numTurns: spawnResult.numTurns,
			sessionId: spawnResult.sessionId,
			branchName,
			issueNumber,
		};

		await writeRunLog(jobId, result);

		// Best-effort notifications (never fail the run)
		await sendNotifications(config, result).catch(() => {});
		if (issueNumber) {
			await postIssueComment({
				repoPath: config.repo.path,
				issueNumber,
				status: result.status,
				prUrl: result.prUrl,
				summary: result.summary,
				jobName: config.name,
			}).catch(() => {});
		}

		return result;
	} catch (error) {
		const isGitError = error instanceof GitOpsError;
		const result: RunResult = {
			status: isGitError ? "git-error" : "error",
			jobId,
			runId,
			startedAt,
			completedAt: new Date().toISOString(),
			durationMs: Date.now() - startTime,
			error: error instanceof Error ? error.message : String(error),
			branchName,
		};

		await writeRunLog(jobId, result).catch(() => {}); // Don't fail on log write error

		// Best-effort notifications on error
		if (config) {
			await sendNotifications(config, result).catch(() => {});
			const errorIssueNumber = result.summary ? extractIssueNumber(result.summary) : undefined;
			if (errorIssueNumber) {
				await postIssueComment({
					repoPath: config.repo.path,
					issueNumber: errorIssueNumber,
					status: result.status,
					error: result.error,
					jobName: config.name,
				}).catch(() => {});
			}
		}

		// Cleanup: if we created a branch but failed, try to go back to base branch
		if (branchName && config) {
			try {
				await execCommand("git", ["-C", config.repo.path, "checkout", config.repo.branch]);
				await execCommand("git", ["-C", config.repo.path, "branch", "-D", branchName]);
			} catch {
				// Cleanup is best-effort
			}
		}

		return result;
	} finally {
		await releaseLock();
	}
}
